version: '3'
services:
    mongodb_consumer:
      hostname: mongodb_consumer
      image: mongo:4.2
      container_name: mongodb_consumer
      restart: always
      entrypoint: [ "/usr/bin/mongod", "--port", "27017", "--bind_ip_all" ]
      ports:
        - "27010:27017"
    mongodb_producer:
        hostname: mongodb_producer
        image: mongo:4.2
        container_name: mongodb_producer
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--port", "27017", "--bind_ip_all" ]
        ports:
          - "27017:27017"